version: '3' 

services:
  redis:
    container_name: l10n-redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mysql:
    container_name: l10n-mysql
    image: mysql/mysql-server:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: l10n 
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - dbdata-l10n:/var/lib/mysql

  pma:
    container_name: l10n-pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    depends_on:
      - mysql
    ports:
      - "80:80"

  web:
    container_name: l10n-web
    image: wyveo/nginx-php-fpm:php74
    links:
      - "mysql:mysql.local"
      - "redis:redis.local"
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:80"
    volumes:
      - ./:/home/apps/l10n
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.aws:/nonexistent/.aws
  
volumes:
  dbdata-l10n:
