version: '3' 

services:
  redis:
    container_name: l10n-redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mysql:
    container_name: l10n-mysql
    image: mysql/mysql-server:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: l10n 
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - dbdata-l10n:/var/lib/mysql

  pma:
    container_name: l10n-pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    depends_on:
      - mysql
    ports:
      - "80:80"

  web:
    image: nginx:latest
    ports:
        - "8080:8080"
        - "8081:8081"
    volumes:
        - ~/.aws:/.aws
        - ./:/home/apps/l10n
        - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  
  php:
    container_name: l10n-php-7.2-fpm
    build: ./
    links:
      - "mysql:mysql.local"
      - "redis:redis.local"
    volumes:
        - ./:/home/apps/l10n
        - ./app/logs/ci/l10n:/var/log/php/ci/l10n
  
volumes:
  dbdata-l10n:
